name: ${project.name}
version: ${project.version}
author: BtoBastian
main: de.oppermann.bastian.safetrade.Main
api-version: 1.16
softdepend: [Vault]
commands:
   trade:
     description: Starts a trade. More information with /trade help!
     aliases: [safetrade]